MopcPrintServer/Controllers/FilesController.cs
using System;
using System.Web.Mvc;
using MopcPrintServer.Models;
using MopcPrintServer.Repository;
using MopcPrintServer.ViewModels;

namespace MopcPrintServer.Controllers
{
    [Authorize]
    public class FilesController : Controller
    {
        private readonly IAplicacionRepository _aplicacionDb;
        private readonly IReporteRepository _reporteDb;

        public FilesController(
            IAplicacionRepository aplicacionDb,
            IReporteRepository reporteDb)
        {
            _aplicacionDb = aplicacionDb;
            _reporteDb = reporteDb;
        }
        // GET: Files
        public ActionResult Add(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index", "Application");
            var aplicacionViewModel = _aplicacionDb.BuscarAplicacionPorId(id.Value);
            if (aplicacionViewModel == null)
                return HttpNotFound();
            var model = new ReporteViewModel
            {
                AplicacionId = id.Value,
                AplicacionNombre = aplicacionViewModel.Nombre,
                AplicacionDescripcion = aplicacionViewModel.Descripcion
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(ReporteViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var nombreArchivo = model.File.FileName;
            if (!nombreArchivo.EndsWith(".frx"))
            {
                model.MensajeError = "El archivo debe ser un reporte de FastReport";
                return View(model);
            }

            var reporte = new Reporte
            {
                Nombre = model.Nombre,
                AplicacionId = model.AplicacionId,
                Identificador = Guid.NewGuid().ToString(),
                ParametrosPrueba = model.ParametrosPrueba
            };

            var ruta = Server.MapPath($"~/App_Data/{reporte.Identificador}");
            model.File.SaveAs(ruta);

            _reporteDb.Add(reporte);
            _reporteDb.SaveChanges();

            return RedirectToAction("Index", "Application");
        }

        public ActionResult Edit(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index", "Application");
            var model = _reporteDb.BuscarReportePorId(id.Value);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ReporteViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var modeloGuardado = _reporteDb.Get(model.Id);
            modeloGuardado.Nombre = model.Nombre;
            modeloGuardado.ParametrosPrueba = model.ParametrosPrueba;

            var nombreArchivo = model.File.FileName;
            if (!nombreArchivo.EndsWith(".frx"))
            {
                model.MensajeError = "El archivo debe ser un reporte de FastReport";
                return View(model);
            }

            var ruta = Server.MapPath($"~/App_Data/{model.Identificador}");
            model.File.SaveAs(ruta);

            _reporteDb.SaveChanges();

            return RedirectToAction("Index", "Application");
        }

        public FileResult DescargarReporte(string identificador)
        {
            var ruta = Server.MapPath($"~/App_Data/{identificador}");
            var fileBytes = System.IO.File.ReadAllBytes(ruta);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, $"{identificador}.frx");
        }
    }
}

MopcPrintServer/Views/Files/Add.cshtml
@model MopcPrintServer.ViewModels.ReporteViewModel
@{
    ViewBag.Title = "Add";
}

<div class="center margent10">
    <h2>@Model.AplicacionNombre - @Model.AplicacionDescripcion</h2>
    <h4>Agregar Reporte</h4>
</div>
<br />
@using (Html.BeginForm("Add", "Files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.AplicacionId)
    @Html.HiddenFor(x => x.AplicacionNombre)
    @Html.HiddenFor(x => x.AplicacionDescripcion)
    <div class="row">
        <div class="col-sm">
            @Html.LabelFor(x => x.Nombre)
            @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Nombre)
        </div>
        <div class="col-sm">
            @Html.LabelFor(x => x.ParametrosPrueba)
            @Html.TextBoxFor(x => x.ParametrosPrueba, new { @class = "form-control", placeholder="Ejemplo: id=5,fecha=2018-05-01" })
            @Html.ValidationMessageFor(x => x.ParametrosPrueba)
        </div>
        <div class="col-sm">
            @Html.LabelFor(x => x.File)
            <input type="file" name="File" value="File" class="form-control" />
            @Html.ValidationMessageFor(x => x.File)
        </div>
    </div>
    <div class="row margent10">
        <div class="col-md">
            <button type="submit" class="btn btn-success">Guardar</button>
        </div>
    </div>
}

@if (!string.IsNullOrEmpty(Model.MensajeError))
{
    <br/>
    <h5 class="field-validation-error">@Model.MensajeError</h5>
}

MopcPrintServer/Views/Files/Edit.cshtml
@model MopcPrintServer.ViewModels.ReporteViewModel
@{
    ViewBag.Title = "Edit";
}

<div class="center margent10">
    <h2>@Model.AplicacionNombre - @Model.AplicacionDescripcion</h2>
    <h4>Volver a Cargar Reporte @Model.Nombre</h4>
</div>
<br />
@using (Html.BeginForm("Edit", "Files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.AplicacionId)
    @Html.HiddenFor(x => x.AplicacionNombre)
    @Html.HiddenFor(x => x.AplicacionDescripcion)
    @Html.HiddenFor(x => x.Identificador)
    <div class="row">
        <div class="col-sm">
            @Html.LabelFor(x => x.Nombre)
            @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Nombre)
        </div>
        <div class="col-sm">
            @Html.LabelFor(x => x.ParametrosPrueba)
            @Html.TextBoxFor(x => x.ParametrosPrueba, new { @class = "form-control", placeholder = "Ejemplo: id=5,fecha=2018-05-01" })
            @Html.ValidationMessageFor(x => x.ParametrosPrueba)
        </div>
        <div class="col-sm">
            @Html.LabelFor(x => x.File)
            <input type="file" name="File" value="File" class="form-control" />
            @Html.ValidationMessageFor(x => x.File)
        </div>
    </div>
    <div class="row margent10">
        <div class="col-md">
            <button type="submit" class="btn btn-success">Guardar</button>
        </div>
    </div>
}

@if (!string.IsNullOrEmpty(Model.MensajeError))
{
    <br />
    <h5 class="field-validation-error">@Model.MensajeError</h5>
}