MopcPrintServer/Controllers/ApplicationController.cs
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MopcPrintServer.Repository;
using MopcPrintServer.ViewModels;

namespace MopcPrintServer.Controllers
{
    [Authorize]
    public class ApplicationController : Controller
    {
        private readonly IAplicacionRepository _aplicacionRepository;
        public ApplicationController(IAplicacionRepository aplicacionRepository)
        {
            _aplicacionRepository = aplicacionRepository;
        }
        // GET: Reports
        public ActionResult Index()
        {
            var model = _aplicacionRepository.BuscarAplicacionesUsuario(User.Identity.GetUserId());
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AplicacionViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            model.UsuarioId = User.Identity.GetUserId(); ;
            model.FechaRegistro = DateTime.Now;
            _aplicacionRepository.Agregar(model);

            return RedirectToAction("Index");
        }
    }
}

MopcPrintServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    @Scripts.Render("~/bundles/modernizr")
    @WebReportGlobals.Scripts()
    @WebReportGlobals.Styles() 
</head>
<body>

@Html.Partial("_navBar")
<div class="container">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

MopcPrintServer/Views/Shared/_PrintLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    @Scripts.Render("~/bundles/modernizr")
    @WebReportGlobals.Scripts()
    @WebReportGlobals.Styles() 
</head>
<body>

<div class="container">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

MopcPrintServer/Views/Shared/_navBar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="@Url.Action("Index", "Home")">
        <img src="~/Content/Images/logo-mopc.svg" alt="Logo MOPC"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav mr-auto">
            <li class="nav-item">
                @Html.ActionLink("Inicio", "Dashboard", "Home", null, new {@class = "nav-link active"})
            </li>
            <li class="nav-item">
                @Html.ActionLink("Mis Aplicaciones", "Index", "Application", null, new {@class = "nav-link active"})
            </li>
        </ul>
        <ul class="nav">
            <li class="nav-item">
                @(!User.Identity.IsAuthenticated ? Html.ActionLink("Iniciar Sesión", "Login", "Home", null, new {@class = "nav-link active"}) : Html.ActionLink("Cerrar Sesión", "CerrarSesion", "Home", null, new {@class = "nav-link active"}))
            </li>
        </ul>
    </div>
</nav>